name: Hexo Deploy

on:
  push:
    branches:
      - master  # 或 master，根据你的源文件分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'  # 使用 Node.js 22.14.0
        
    - name: Install dependencies
      run: npm install
    
    - name: Generate static files
      run: npx hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages  # 部署到的分支